services:
  redis:
    image: "redis:alpine"
    container_name: linkhub-redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: linkhub-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss
    container_name: linkhub-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus